---
title: "Help Index"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Jump to sections or pages using the links below:

| [bayz() function](#Main-function-bayz)            | Model-term features and options | Output use |
| [Model formula](#Model-formala)                   | Interaction specifications | General summary |
| [Residual variance (Ve)](#Coefficients estimates) | Nested regressions         | Extract estimates (estim, coef, fixef, ranef) |
| [data frame](#Variance components and PVEs)       |                            | Extracts variances, hyper-pars, and functions (vhest) |
| [linking kernels, features (linkid)](#Computing constrasts) |                  | Convergence diagnostics (conv) |
| [MCMC chain]                                      | Variance specification (V) | Trace and density plots (plot)|
| [workdir in/output]                               | Reduced rank (dim, dimp)   | Warnings and errors |
| [initial values (init)]                           | trace and save options     | | 
| [verbose settings]                                | linkid on rr() term        | | 

 
-   [summary](#Summary of output)
-   [coef, fixef and ranef](#Coefficients estimates)
-   [vcomp](#Variance components and PVEs)
-   [Computing contrasts](#Computing constrasts)


## Model formula


## Residual variance (Ve)

## Data frame (data)

## linking kernels, features (linkid)

## MCMC chain settings

## workdir in/output

## initial values (init)

## verbose settings


# Output use
Use of summary() on the bayz output object produces a summary of parameter estimates from the fitted model
including convergence diagnostics and Highest Posterior Density (HPD) regions. 

The summary() method only lists a limited number of the so-called "traced" parameters - these are model-parameters
for which all MCMC samples are saved in the output, allowing to compute convergence, HPD regions, and to plot traces
and densities (using plot()). The traced parameters by default include: all scalar variance parameters, estimated
variance-covariances up to dimension 4x4, the model mean, scalar regression coefficients,
coefficient estimates from fixed effects with up to 4 levels, and nested regressions with up to 4 levels. 


# Coefficients estimates

Apart from using these functions, it is also quite straightforward to extract estimates directly from the bayz output object.
All estimates are stored in the output in a list called <output>$Estimates, which has named elements according to parameter names.


# Variance components and PVEs

The vcomp() method extracts variance estimates from the output.

